---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: accounting-storage-scan
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
          - name: accounting-storage-service
            image: registry.cloud.sdu.dk/sdu-cloud/accounting-storage-service:1.2.5
            command:
            - /opt/service/bin/service
            - --config-dir
            - /etc/refresh-token
            - --config-dir
            - /etc/token-validation
            - --config-dir
            - /etc/psql
            - --scan
            volumeMounts:
            - mountPath: /etc/refresh-token
              name: refresh-token
            - mountPath: /etc/token-validation
              name: token-validation
            - mountPath: /etc/psql
              name: psql

          volumes:
          - name: refresh-token
            secret:
              optional: false
              secretName: accounting-storage-refresh-token
          - name: token-validation
            configMap:
              name: token-validation
          - name: psql
            secret:
              secretName: accounting-storage-psql

          imagePullSecrets:
            - name: esci-docker
