---
apiVersion: v1
kind: Service
metadata:
  name: app-kubernetes-watcher
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app-kubernetes-watcher
      prefix: ^/api/app/kubernetes/watcher(/.*)?$
      prefix_regex: true
      service: app-kubernetes-watcher:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-kubernetes-watcher
