def initialize() {
  try {
    stage('build and backend') {
      sh '''cd backend
      ./gradlew clean
      ./gradlew generateBuildConfig
      ./gradlew build'''
    }
  } catch (e) {
    echo "Build Failed"
    def log = currentBuild.rawBuild.getLog(50)
    def startIndex = log.indexOf("FAILURE:")
    def endIndex = log.indexOf("* Try:")
    return 'FAILURE\n' + 'BackendFailed: \n' + log.subString(startIndex, endIndex+1)
  } finally {
    publishHTML([
        allowmissing: false,
        alwaysLinkToLastBuild: false,
        keepAll: true,
        reportDir: 'backend/build/reports/detekt',
        reportFiles: 'detekt.html',
        reportName: 'Backend Detekt',
        reportTitles: ''
    ])
  }
  return 'SUCCESS'
}

return this
