def initialize() {
  try {
    stage('build and backend') {
      sh '''cd backend
      ./gradlew clean
      ./gradlew generateBuildConfig
      ./gradlew build'''
    }
  } catch (e) {
    echo "Build Failed"
    return 'FAILURE\n' + 'BackendFailed: \n' + currentBuild.rawBuild.getLog(50)
  } finally {
    publishHTML([
        allowmissing: false,
        alwaysLinkToLastBuild: false,
        keepAll: true,
        reportDir: 'backend/build/reports/detekt',
        reportFiles: 'detekt.html',
        reportName: 'Backend Detekt',
        reportTitles: ''
    ])
  }
  return 'SUCCESS'
}

return this
