apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
        - name: jenkins-startup
          image: alpine:3
          command:
            - chown
            - -R
            - 1000:2000
            - /var/jenkins_home
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk11
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          securityContext:
            runAsUser: 1000
            runAsGroup: 2000
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins

