apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  mountOptions:
  - _netdev
  persistentVolumeReclaimPolicy: Retain
  rbd:
    image: jenkins
    keyring: /etc/ceph/keyring
    monitors:
    - 10.135.0.15:6789
    - 10.135.0.16:6789
    - 10.135.0.17:6789
    pool: kube
    secretRef:
      name: ceph-secret-kube
      namespace: kube-system
    user: kube
  storageClassName: rbd
  volumeMode: Filesystem
