---
apiVersion: v1
kind: Service
metadata:
  name: rpc-test
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: rpc-test
      prefix: ^/api/rpc/test(/.*)?$
      prefix_regex: true
      service: rpc-test:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpc-test
