---
apiVersion: v1
kind: Service
metadata:
  name: support
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: support
      prefix: ^/api/support(/.*)?$
      prefix_regex: true
      service: support:8080
      rewrite: ""

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: support-service
