def initialize() {

	try {
	  stage('build storage-service') {
	    sh '''cd storage-service
	    ./gradlew clean
	    ./gradlew build -x test'''
	  }
	} catch (e) {
    echo "Build Failed"
    return 'FAILURE'
  } finally {
    publishHTML([allowmissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'storage-service/build/reports/detekt', reportFiles: 'detekt.html', reportName: 'storage-service-detekt-Report', reportTitles: ''])
  }

  try {
    stage('test storage-service') {
      container('docker') {
        sh '''
          apk add --no-cache openjdk8
          apk add --no-cache gradle=4.8.1-r0  
          apk add --no-cache nss'''
        sh '''cd storage-service
        ./gradlew test'''
      }
    } 
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}	

return this
