replicas: 2

clusterName: "elasticsearch"
nodeGroup: "client"
masterService: "elasticsearch-master"

#esMajorVersion: 6
#imageTag: "6.8.1"
imageTag: "7.6.0"

roles:
  master: "false"
  ingest: "true"
  data: "false"

esJavaOpts: "-Xmx8g -Xms8g"

resources:
  limits: 
    cpu: "2000m"
    memory: "12Gi"
  requests:
    cpu: "2000m"
    memory: "12Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "rbc"
  resources:
    requests:
      storage: 1Gi # Currently needed till pvcs are made optional

persistence:
  enabled: false

service:
  type: NodePort