replicas: 3

clusterName: "elasticsearch"
nodeGroup: "newclient"
masterService: "elasticsearch-newmaster"

#esMajorVersion: 6
#imageTag: "6.8.1"
#imageTag: "7.5.0"

roles:
  master: "false"
  ingest: "false"
  data: "false"

esJavaOpts: "-Xmx8g -Xms8g"

resources:
  limits: 
    cpu: "2000m"
    memory: "14Gi"
  requests:
    cpu: "2000m"
    memory: "14Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "rbc"
  resources:
    requests:
      storage: 1Gi # Currently needed till pvcs are made optional

persistence:
  enabled: false

service:
  type: NodePort