---
apiVersion: batch/v1
kind: Job
metadata:
  name: appStore-move-tags
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
      - name: app-store
        image: registry.cloud.sdu.dk/sdu-cloud/app-store-service:0.3.6.RC-4
        command:
        - /opt/service/bin/service
        - --config-dir
        - /etc/refresh-token
        - --config-dir
        - /etc/token-validation
        - --config-dir
        - /etc/psql
        - --move
        volumeMounts:
        - mountPath: /etc/refresh-token
          name: refresh-token
        - mountPath: /etc/token-validation
          name: token-validation
        - mountPath: /etc/psql
          name: psql

      volumes:
      - name: refresh-token
        secret:
          optional: false
          secretName: app-store-refresh-token
      - name: token-validation
        configMap:
          name: token-validation
      - name: psql
        secret:
          secretName: app-store-psql

      imagePullSecrets:
      - name: esci-docker
