def initialize() {
  
  try {
    stage('test app-orchestrator-service') {
      sh '''cd app-orchestrator-service
      ./gradlew test'''
    }
  } catch (e) {
    echo "Test FAILED"
    return 'UNSTABLE'
  }
  return 'SUCCESS'
}

return this
