---
apiVersion: v1
kind: Service
metadata:
  name: filesearch
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: filesearch
      prefix: ^/api/file-search(/.*)?$
      prefix_regex: true
      service: filesearch:8080
      rewrite: ""
      precedence: 10
      headers:
        x-no-load: true

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: filesearch-service
